-- Seed races
-- Changed FALSE to 0 and TRUE to 1 for SQLite boolean compatibility
INSERT INTO events (
  id,
  title,
  tagline,
  type,
  date,
  time,
  location,
  depart_from,
  distances,
  description,
  registration_url,
  registration_deadline,
  highlights,
  unique_feature,
  key_features,
  accent_color,
  image_url,
  is_recurring,
  is_featured_homepage,
  display_order
)
VALUES
  (
    'f3-lake-half',
    'F³ Lake Half Marathon & 5K',
    'Run the Lakefront, Finish at Soldier Field',
    'race',
    '2026-01-17',
    '10:00 AM',
    'Soldier Field',
    'South Loop',
    '["Half Marathon", "5K"]',
    'Experience Chicago''s most scenic winter race! The F³ Lake Half Marathon and 5K takes you along the beautiful lakefront trail with stunning views of Lake Michigan and the Chicago skyline. Start and finish at the iconic Soldier Field, home of the Chicago Bears. This fast, flat course is perfect for setting a PR or enjoying a scenic winter run with friends.',
    'https://www.f3lakehalf.com/register',
    '2026-01-10',
    '["Flat & fast lakefront course", "Scenic views of Lake Michigan", "Finish inside Soldier Field", "Post-race party with food & drinks"]',
    'Finish line inside historic Soldier Field!',
    '[{"icon":"award","label":"PR-Friendly Course","color":"blue"},{"icon":"users","label":"Group Training","color":"purple"},{"icon":"medal","label":"Finisher Medals","color":"amber"}]',
    'from-blue-500 to-cyan-500',
    '/chicago-lakefront-running-soldier-field-skyline.jpg',
    0,
    1,
    4
  ),
  (
    'miles-per-hour',
    'Miles Per Hour Run',
    'Challenge Yourself Every Hour',
    'race',
    '2026-02-14',
    '8:00 AM',
    'Grant Park',
    'South Loop',
    '["Marathon", "Half Marathon", "10K"]',
    'A unique endurance challenge where you run one mile at the start of every hour! Choose your distance: marathon (26 miles over 26 hours), half marathon (13 miles over 13 hours), or 10K (6.2 miles over 7 hours). This timed event tests your pacing strategy and mental toughness. With 59 minutes of rest between each mile, it''s a perfect introduction to ultra-distance challenges.',
    'https://www.milesperhourrun.com/register',
    '2026-02-07',
    '["Unique format - 1 mile per hour", "Multiple distance options", "59 minutes rest between miles", "Perfect for first-time ultra runners"]',
    'Experience ultra running in a beginner-friendly format!',
    '[{"icon":"clock","label":"Hourly Miles","color":"green"},{"icon":"brain","label":"Mental Challenge","color":"purple"},{"icon":"coffee","label":"Rest Periods","color":"amber"}]',
    'from-green-500 to-emerald-600',
    '/mccormick-place-chicago-auto-show-indoor-running.jpg',
    0,
    1,
    5
  );
